### ISSUE TITLE
The value of the 'access-control-allow-origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

### ISSUE THREAD

**Issue by jayar95** [node-facebook/facebook-node-sdk#102]
Attached is a screenshot of the logged error thrown when making any type of request to the facebook API.

 

```javascript
let endpoint = endpoints.pageList(userId);

fb.setAccessToken(accessToken);

fb.api(endpoint, res => {
	if (res && !res.error)
		this.saveFbObjects(res, methodCall.pageCreate);
});
```

 

![Image of Screenshot](http://i.imgur.com/xCsbpkh.png)

**Comment by dantman** [comment]
Please explain what context you are using `fb` in that results in XmlHttpRequest being used?

**Comment by rgnevashev** [comment]
![2017-10-06_13-44-29](https://user-images.githubusercontent.com/123600/31274661-8ada6b68-aa9c-11e7-93fb-d37659378d01.png)
I got same the error I use fb in the client env

**Comment by rgnevashev** [comment]
https://github.com/request/request/issues/986

**Comment by rgnevashev** [comment]
![2017-10-06_14-29-28](https://user-images.githubusercontent.com/123600/31276103-d123ada4-aaa2-11e7-88a6-c5f534b63635.png)
I've added the option withCretentials: false and client env works now

By the way, do you plan replace request with native fetch? It would be wonderful

**Comment by jayar95** [comment]
They closed my request because it's not documented as an option; however, it does work.

**Comment by dantman** [comment]
@rgnevashev This is a server library not a client library. Replacing request/Node.js HTTP with the browser exclusive `fetch` would break the library for 99% of the library's users.

I still haven't been given an explanation to why people are using this library in the client instead of Facebook's own client side SDK.
