### ISSUE TITLE
Can I use this sdk to get realtime Graph API data ?

### ISSUE THREAD

**Issue by sohaeb** [node-facebook/facebook-node-sdk#104]
I want to be able to fetch data from graph-api in realtime. 

i.e: If I post on fb, I want to fetch this post at the same time and then I can send a push notification to mobile users. Is this possible ?

**Comment by dantman** [comment]
This is a SDK for making graph API calls, you can use it to do anything you can do with the graph API.

For documentation on how the graph API works see Facebook's documentation: https://developers.facebook.com/docs/graph-api
For questions on how to use Facebook's graph API, use the [Facebook tag on StackOverflow](https://stackoverflow.com/questions/tagged/facebook).

I suggest looking up the Graph API's read-after-write documentation:
https://developers.facebook.com/docs/graph-api/using-graph-api#read-after-write

You may also be interested in Webhooks:
https://developers.facebook.com/docs/graph-api/webhooks

**Comment by sohaeb** [comment]
Thank you for the reply and the help. 

I guess as I thought, Facebook doesn't have the feature that allow us to get realtime data like what Twitter have: ([Twitter Streaming](https://dev.twitter.com/streaming/overview))
