### ISSUE TITLE
An access token is required to request this resource.

### ISSUE THREAD

**Issue by chandan7193** [node-facebook/facebook-node-sdk#105]
I not able to login using this npm 
This is my code
`
import React, { Component } from 'react';
import { Grid } from 'semantic-ui-react';
import {FB, FacebookApiException} from 'fb';
import './SignUp.css';

class SignUp extends Component{

	constructor(props) {
		super(props);
		this.handleLogin = this.handleLogin.bind(this);
	}

	componentDidMount() {
		FB.options({version: 'v2.5',appId: 'xxx', appSecret: 'xxxx'});
		
	}

	handleLogin(e: any){
		FB.api('4', { fields: ['id', 'name'] }, function (res) {
		  if(!res || res.error) {
		    console.log(!res ? 'error occurred' : res.error);
		    return;
		  }
		  console.log(res.id);
		  console.log(res.name);
		});
	};

	
	render(){
		return(
			<div className="message">
			<Grid divided="vertically" columns="equal">
			<Grid.Row>
			<Grid.Column>
			<div className="UserDetails">
				<button className="button" onClick={this.handleLogin}>Login</button>
			</div>
			</Grid.Column>
			</Grid.Row>

			</Grid>
			</div>

			);
	}
}
export default SignUp;
`

Console is showing me message

**GET https://graph.facebook.com/v2.5/4?fields=%5B%22id%22%2C%22name%22%5D 400 ()**

**Object {message: "An access token is required to request this resource.", type: "OAuthException", code: 104, fbtrace_id: "BvsKVSG1Xo1"}**

**Comment by dantman** [comment]
You're not logging in at all. All you're doing is making an api call to /4.

Additionally this is a node js (server side) library not a client. You have to handle login separately using a manual login flow or Facebook's client sdk.
