### ISSUE TITLE
version code breaks

### ISSUE THREAD

**Issue by matt212** [node-facebook/facebook-node-sdk#108]
Hi,
I am using fb node sdk for some time and works as expected , but when i try to build new project and did
"npm install fb" it worked but when i ran my code 
it gives below error
![issue](https://user-images.githubusercontent.com/1698139/28240885-07ea918c-69a7-11e7-8ca6-d33dd40a2079.png)
any recommendations on how to resolve it !

**Comment by dantman** [comment]
What version of node are you running?

The babel build is targeting node 4, node has supported template literals like those since v4, so it sounds like you're not running a new enough version of node.

**Comment by matt212** [comment]
hi , 
this is my node and npm version !
![asas](https://user-images.githubusercontent.com/1698139/28241069-fa2d461c-69aa-11e7-92da-f76e75aceca3.png)
which node version should be compatible enough with fb node package ?

**Comment by dantman** [comment]
Minimum supported node version is 4, but it would be preferred to stick with at least the current LTS (6).
