### ISSUE TITLE
Get the facebook login status

### ISSUE THREAD

**Issue by campanagerald** [node-facebook/facebook-node-sdk#110]
Hello, I just want to share a link using facebook-node-sdk

My alogrithm is:

1. http call /share
2. get the login status
3. if user is not already logged in -> return a login link using getLoginUrl()
4. http call again the /share?accessToken="******"
5. post the link using the post api of facebook-node-sdk

My problem is how can I get login status?
Is there counter part of this code in this nodejs facebook sdk

FB.getLoginStatus(function(response) {
  if (response.status === 'connected') {
    // the user is logged in and has authenticated your
    // app, and response.authResponse supplies
    // the user's ID, a valid access token, a signed
    // request, and the time the access token 
    // and signed request each expire
    var uid = response.authResponse.userID;
    var accessToken = response.authResponse.accessToken;
  } else if (response.status === 'not_authorized') {
    // the user is logged in to Facebook, 
    // but has not authenticated your app
  } else {
    // the user isn't logged in to Facebook.
  }
 });

Thanks.

**Comment by dantman** [comment]
No, this SDK is a server side library. The server doesn't have access to the Facebook session in your browser. You have to get the access_token client side and then pass it to the server. Of if you don't want to use JS on the client you'll have to always go through the manual login flow (it should automatically redirect back if the user is already logged in).
