### ISSUE TITLE
Always return 'Invalid appsecret_proof provided in the API argument'

### ISSUE THREAD

**Issue by juanarbol** [node-facebook/facebook-node-sdk#111]
:/ This works only few times (of course I've checked my `appId`, `appSecret` and `access_token` I do not know why is not working.

**Comment by Fibonacci-Solucoes-Ageis** [comment]
I'm having the same problem.

**Comment by sandrocsimas** [comment]
How did you fixed this issue? The same is happening now here.

**Comment by juanarbol** [comment]
I wasn't sending correct data to API.

**Comment by sandrosimas** [comment]
Yes, this happen when you use an app secret from another app.
