### ISSUE TITLE
Error when upload photos to FB with buffer

### ISSUE THREAD

**Issue by HoneyryderChuck** [node-facebook/facebook-node-sdk#112]
I'm having issues with the `source` parameter when uploading photos, namely I get the following error: 

```js
{ message: '(#324) Requires upload file',
  type: 'OAuthException',
  code: 324,
  fbtrace_id: 'CSYu+GDO4kD' }
```

My call looks like this: 

```js
const params = {
  access_token: this.token,
  appsecret_proof: this.proof,
  source: {
    value: buffer,
    options: { contentType: 'image/jpeg' }
  },
  caption: 'Whatever'
}
return netw Promise((resolve, reject) => {
  FB.api('/me/photos', 'post', params, (res) => {
...
```

The value passed is of type `Buffer`, I've been reading around that there are some issues with this, that `fb` doesn't support `multipart/form-data`, and all other things I'm believing not to be true. What am I doing wrong in this case?

**Comment by dantman** [comment]
Firstly make sure you're on `1.1.0` or higher.

The upload data is just passed on to `request` so a lot of what works and doesn't is related to that. However others have suggested that it may be necessary to include a `filename` value in the `options` object for your upload.

**Comment by HoneyryderChuck** [comment]
I'm using 2.0.0. 

Passing filename didn't work. 

So what you're saying is that `request` doesn't support buffers? tcpdump shows me valid multipart requests being generated, so I think that this might be a limitation of facebook's API or this lib. 

This is the header generated for the file read stream call:

```
POST /upload HTTP/1.1
host: localhost:8081
content-type: multipart/form-data; boundary=--------------------------233609602348747924052186
content-length: 46205
Connection: close
```

This is the one that fails (with the parameters):

 ```
POST /upload HTTP/1.1
host: localhost:8081
content-type: multipart/form-data; boundary=--------------------------097291422519796292400657
content-length: 46205
Connection: close

----------------------------097291422519796292400657
Content-Disposition: form-data; name="source"; filename="about-banner.jpg"
Content-Type: image/jpeg
```

**Comment by TakenakaSimon** [comment]
I'm getting this exact same error. Did you ever find a solution?

I want to avoid saving everything locally once if I can.

**Comment by HoneyryderChuck** [comment]
@TakenakaSimon I'm sorry, but I don't have a good answer. Yes, I'm saving to a file **then** uploading. The best I can tell you is: use a tempfile package/ store to `/tmp`, in most cases it should not go beyond using RAM. But yes, it sucks.

**Comment by nbar1** [comment]
Can we get an actual solution to uploading from buffer?

**Comment by joturako** [comment]
@HoneyryderChuck please check the updated README #131 and close the issue if it's solved for you.

**Comment by HoneyryderChuck** [comment]
It might take some time til I do that. I'll reopen if still not working
