### ISSUE TITLE
Error: getaddrinfo ENOTFOUND graph.facebook.com

### ISSUE THREAD

**Issue by JCarlosR** [node-facebook/facebook-node-sdk#116]
Hi.
I am trying to scrape my page again requesting it to the graph api:

```
		// scrape again via facebook api
		const options = {
			appId      : '1927847517490935',
			appSecret  : 'xxx',
			accessToken: 'zzz',
		    version    : 'v2.10'
		};
		FB.options(options);
		const params = {
			id: url,
			scrape: true
		};
		FB.api('/', 'post', params, function (res) {
			if (!res || res.error) {
				console.log(!res ? 'error occurred' : res.error);
				return;
			}
		});
```

But I get the next error message:

> { Error: getaddrinfo ENOTFOUND graph.facebook.com graph.facebook.com:443 at errnoException (dns.js:28:10) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26) code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'graph.facebook.com', host: 'graph.facebook.com', port: 443 } |  

Can you please help me?

**Comment by dantman** [comment]
Firstly, please don't include your appSecret or accessToken in bug reports. You should reset your app secret now.

ENOTFOUND errors are generally thrown by the low level networking stack. Either there's something wrong with your dns or network connection and it can't connect to the graph API or perhaps https isn't setup right on your server.

**Comment by JCarlosR** [comment]
@dantman Sorry. I was thinking that the facebook-node-sdk uses HTTP instead of HTTPS.
But that's not true. The problem was with my server as you said.
Firebase cloud functions doesn't allow to perform external requests for free accounts.
Thank you for your help.

**Comment by dantman** [comment]
@JCarlosR Defaulting to insecure would be a poor choice. Facebook doesn't even allow usage over HTTP anyways.
