### ISSUE TITLE
'fields' option not added my GET url

### ISSUE THREAD

**Issue by fatahn** [node-facebook/facebook-node-sdk#121]
I am using the promised based interface. I am trying to get likes and comments data on a FB post

```
  FB
      .api(`/${postId}`, {
                 fields: ['likes', 'comments'], // tried 'fields': ['name'] too
                 access_token: FB_ACCESS_TOKEN
              })
      .then(res => { console.log(res)}
)
```
I get a console error but also shows fields was ingnored
`request.js:132 GET https://graph.facebook.com/v2.3/1512056032174564?access_token=<access_token>`

Is this an issue with fb or request.js. Any Ideas? Thanks in advance

**Comment by dantman** [comment]
This code is responsible for serializing the query params:
https://github.com/node-facebook/facebook-node-sdk/blob/master/src/fb.js#L62-L76

Unless you have an access_token defined in the options, indicating that the params could be ignored entirely and the access_token come from the option; that code should be the only place that could be responsible for this.

The only difference between the two params seems to be the fact that one is an array. However turning that into json is a simple filter and shouldn't be responsible for making a param disappear.

Could you try using a variety of different params (some strings, some numbers, some arrays, and some object) and include more than just the two.

eg: `{a: 'a', b: 1, c: {x:'y'}, d: ['a', 'b'], e: true}`
