### ISSUE TITLE
Call a function or promise once the login is over

### ISSUE THREAD

**Issue by rahulbasu710** [node-facebook/facebook-node-sdk#122]
I am using `JWT & CORS Authenticated` middleware. So i am doing something like 
```
router.get('/signup/facebook/:id', (req, res) => {
  const redirectLink = urldecode(req.params.id);
  const loginURL = FB.getLoginUrl({
    client_id: '1862357220760064',
    redirect_uri: redirectLink,
  }, result => console.log(result));
  res.send(loginURL);
});
```
I am sending the URL as a response 
After the login is completed, I want to call `Fb.api()` to get user's details like `id, displayName` from there & then use it with my database

**Comment by dantman** [comment]
I don't know what `:id` is but that doesn't look right. You need a second handler to receive the OAuth response from Facebook when the user authorizes your app. And the URI for **that** is supposed to be the `redirect_uri`.

```js
}, result => console.log(result));
```
FB.getLoginUrl is not async, there is no callback argument. It just helps you build the URL to send the user to.

```js
res.send(loginURL);
```
You're supposed to send the user TO the url, typically this is done by a HTTP temporary redirect to that URL. This looks like you're returning it back to js as plaintext.

Please re-read https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow
