### ISSUE TITLE
Syntax Error when using Complex fields

### ISSUE THREAD

**Issue by nfatah** [node-facebook/facebook-node-sdk#123]
Hi I am using redux and get a facebook graph api error when my code has complex fields like so:

```
    dispatch(trackPostLoading(true))
    return FB.api(
      `/${postId}`,
      {
        fields: [
          'likes.limit(1000){id}',
          'comments.limit(1000){id}{from}',
          'sharedposts{id}'
        ]
      }
    ).then(res => { do something....
```

Bu the code only works fine if the code is just
```
    dispatch(trackPostLoading(true))
    return FB.api(
      `/${postId}`,
      {
        fields: [
          'likes'
          'comments'
          'sharedposts'
        ]
      }
    ).then(res => { do something ... 
```
the eroor i get 
`Err
or tracking post {"error":{"message":"Syntax error \"Expected end of string instead of \"{\".\" at character 46: likes.limit(1000){id},comments.limit(1000){id}{from},sharedposts{id}","type":"OAuthException","code":2500,"fbtrace_id":"G6rwRH4NLpC"}}
`

**Comment by dantman** [comment]
If you want to use an array for `fields` put a `.join(',')` at the end. The `fields` parameter is **not** a complex field, the Graph API defines it as a comma separated string.
