### ISSUE TITLE
First argument must be a string or Buffer

### ISSUE THREAD

**Issue by NeXTs** [node-facebook/facebook-node-sdk#130]
As mentioned in "Publishing a multi-photo story" section of [FB docs](https://developers.facebook.com/docs/graph-api/photo-uploads) there is `published` parameter which is boolean.
![Publishing a multi-photo story](https://scontent.fods1-1.fna.fbcdn.net/v/t39.2178-6/13178089_1720826261520580_2112713042_n.png?oh=bd03ad4bfc79a86b6a336918afe92c38&oe=5ADC2B7E)

While uploading image to facebook using buffer, this parameter may throw an error "First argument must be a string or Buffer"
This library missed this parameter for [upload example](https://github.com/node-facebook/facebook-node-sdk#upload)

But if we set it as:
```
FB.api('me/photos', 'post', {
    source: { value: photoBuffer, options: { contentType: 'image/jpeg' } },
    caption: 'My vacation',
    published: false      //  <-------  here it is
}, function (res) {
  if(!res || res.error) {
    console.log(!res ? 'error occurred' : res.error);
    return;
  }
  console.log('Post Id: ' + res.post_id);
});
```

"First argument must be a string or Buffer" error will occur.
It appears to be that boolean parameters [aren't supported by form-data](https://github.com/request/request/issues/1761#issuecomment-138541296)

To work out around this, just change it's value to `0` or `1`.
Maybe this case should be handled by library? Or at least add note about this in docs. It may save few hours to someone.

**Comment by mnooblet** [comment]
please mention that somewhere on the first page below the upload example...
