### ISSUE TITLE
Can not call FB.logout()

### ISSUE THREAD

**Issue by NguyenVanVu-K58CA** [node-facebook/facebook-node-sdk#146]
TypeError: _fb2.default.logout is not a function

**Comment by dantman** [comment]
This library is not a client side library, it's a server side SDK. It cannot log the user out of Facebook, it's only possible for it to make API calls with access tokens it is given by other means.

Please use Facebook's own client side JavaScript SDK.
https://developers.facebook.com/docs/javascript
