### ISSUE TITLE
Publish pre-compiled code to npm

### ISSUE THREAD

**Issue by arungalva** [node-facebook/facebook-node-sdk#147]
I was trying to use this with create-react-app. However, I can't run a production build because this library has some ES6 code published to npm.

Please refer to this link for the error 
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by dantman** [comment]
I just tried installing both `fb` and `fb@next`, both versions only include compiled ES5 code. I haven't even included the source version or a modules version as of yet. Could you show me the actual error you are getting.

**Comment by Aubron** [comment]
I'm also receiving this issue: 
```
yarn run v1.3.2
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/fb/lib/fb.js:130 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

**Comment by Aubron** [comment]
runinng the file (fb.js) through JSHint shows a lot of ES6 issues, including the following:

```
634 | 'template literal syntax' is only available in ES6 (use 'esversion: 6').
681 | 'object short notation' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
686 | 'object short notation' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
```
