### ISSUE TITLE
FB.api(id) Throwing error

### ISSUE THREAD

**Issue by akashdathan** [node-facebook/facebook-node-sdk#148]
{ 
 message: '(#12) singular statuses API is deprecated for versions v2.4 and higher',
  type: 'OAuthException',
  code: 12,
  fbtrace_id: 'Bdgw2PZxevX'
}

**Comment by dantman** [comment]
https://developers.facebook.com/docs/graph-api/changelog/archive
> GET /v2.4/{id}/links and GET /v2.4/{id}/statuses will no longer be available beginning in v2.4. As an alternative, we suggest using GET /v2.4/{id}/feed.

You are making an API call that Facebook no longer supports, please update your code. This is not a bug in this SDK.
