### ISSUE TITLE
Getting error 'An active access token must be used to query information about the current user.'

### ISSUE THREAD

**Issue by N-W-Turash** [node-facebook/facebook-node-sdk#149]
Hi, I am using this module to make a call to facebook graph api.
Heres my code: 

`FB.api('oauth/access_token', {
    client_id: '*****************',
    client_secret: '********************',
    grant_type: 'client_credentials'
}, function (res) {
    if(!res || res.error) {
        console.log(!res ? 'error occurred' : res.error);
        return;
    }

    var accessToken = res.access_token;
    var expires = res.expires ? res.expires : 0;

    console.log('res->', res);
    console.log('accessToken->', accessToken);
    console.log('expires->', expires);

    FB.setAccessToken(accessToken);

    FB.api('me', { fields: 'id,name', access_token: accessToken }, function (res) {
        console.log(res);
    });
});`

But I am getting the following error:

`{ error:
   { message: 'An active access token must be used to query information about the current user.',
     type: 'OAuthException',
     code: 2500,
     fbtrace_id: 'HuCdL7CI6iA' } }`

What can I do?

**Comment by dantman** [comment]
`grant_type=client_credentials` is used to get an **App** access token. App access tokens are not associated with any user (there is no "me") and do not have access to any user's personal information.

You need to get a user access token. Either use the [official client side JavaScript SDK](https://developers.facebook.com/docs/facebook-login/web) to give the user a login and then submit that access token to the server and extend it. Or use the [Manually Build a Login Flow](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow) technique to use an OAuth redirect based flow and get the access token in the `redirect_uri`'s handler and save it to the database.
