### ISSUE TITLE
Log the user out of facebook?

### ISSUE THREAD

**Issue by andithemudkip** [node-facebook/facebook-node-sdk#170]
sorry if i'm just being a newbie here but i've been searching around for hours and i can't seem to find a way to log the user out after successfully logging in.

**Comment by dantman** [comment]
If you are acquiring login tokens with the client side SDK use `FB.logout` on the client. If you are using a server side manual login flow, see the end of the https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow page.
