### ISSUE TITLE
An active access token must be used to query information about the current user.

### ISSUE THREAD

**Issue by Araknos** [node-facebook/facebook-node-sdk#177]
Hello,
It's more a question than an issue, sorry about that.
I'm writing a program in nodejs that post a photo on my page (I also create an app for it). It's a pain finding a solution and I'm just discovering FB api. Maybe it's just not possible.
I tried facebook-node-sdk and wrote that:

`
const FB = require("FB").default;
const fs = require("fs");

FB.api('oauth/access_token', {
   client_id: '***',
   client_secret: '***',
   grant_type: 'client_credentials'
}, function (res) {
   if (!res || res.error) {
      console.log(!res ? 'error occurred' : res.error);
      return;
   }

   FB.setAccessToken(res.access_token);

   FB.api('me/photos', 'post', { source: fs.createReadStream("./avatar.png"), caption: 'Hello world' }, function (res) {
      if(!res || res.error) {
        console.log(!res ? 'error occurred' : res.error);
        return;
      }
      console.log('Post Id: ' + res.post_id);
    });
});
`

But i'm getting the following error:

> message: 'An active access token must be used to query information about the current user.',
> type: 'OAuthException',
> code: 2500,

Is it possible ? How to do that ?
Thank's a lot !

**Comment by dantman** [comment]
`grant_type: 'client_credentials'` returns a client/app access token for your app as a whole and not a specific user. So you can only use it to query for things that are not related to any specific user and do not need to be made from a user's perspective.

You'll need a user access token (or alternatively a page access token for page stuff).

To get a user access token you either need to use the official client side SDK and use `FB.login` to get a token then pass that to your server; implement the [manual login flow](https://github.com/node-facebook/facebook-node-sdk#manual-login-flow) to login the user; or for a cli script you might be able to use the [Graph API Explorer](https://developers.facebook.com/tools/explorer/) to get an access token and then manually pass it to your script with an arg/env variable.

**Comment by Emericano** [comment]
Thank you for your quick answer dantman !
I followed your advices and saw this so: https://stackoverflow.com/questions/17197970/facebook-permanent-page-access-token
I'm getting now: (#200) This endpoint is deprecated since the required permission publish_actions is deprecated

**Comment by Araknos** [comment]
Thank you for your quick answer dantman !
I followed your advices and saw this so: https://stackoverflow.com/questions/17197970/facebook-permanent-page-access-token
I'm getting now: (#200) This endpoint is deprecated since the required permission publish_actions is deprecated
