### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by dpriskorn** [node-facebook/facebook-node-sdk#184]
I looked in this repo and in the forks and none seem viable. Anybody up for picking up the stick?

**Comment by dantman** [comment]
Is anything broken in the current release?

**Comment by dpriskorn** [comment]
I did not try it to be honest.

**Comment by alexv95** [comment]
@egils-consulting i tried the original module for nodejs, to perform get request on the graph api ("fb" module on npm) and its working without any issue

**Comment by bensleveritt** [comment]
Can we close this?
