### ISSUE TITLE
How to get login status FB.getLoginStatus does not work

### ISSUE THREAD

**Issue by S-codes14** [node-facebook/facebook-node-sdk#188]
How to get login status FB.getLoginStatus does not work, even though the function is available on the sdk

**Comment by dantman** [comment]
FB.getLoginStatus is part of the [Facebook's official **client-side** SDK](https://developers.facebook.com/docs/javascript/). This is a **server-side** Node.js SDK and does not have that functionality. You cannot check login status from the server, you need to use Facebook's official SDK to do that on the client.

**Comment by S-codes14** [comment]
thanks
