### ISSUE TITLE
Search user for mentioning 

### ISSUE THREAD

**Issue by Albinzr** [node-facebook/facebook-node-sdk#189]
How can I search users so that I can mention them in the post?. Is there any specific API for this or does it require specific permission?

**Comment by dantman** [comment]
Please check Facebook's own [Graph API documentation](https://developers.facebook.com/docs/graph-api/).

**Comment by Albinzr** [comment]
> Please check Facebook's own [Graph API documentation](https://developers.facebook.com/docs/graph-api/).

This is not mentioned in documentation, That's why I asked

**Comment by dantman** [comment]
> This is not mentioned in documentation, That's why I asked

Then try Facebook's official developer [support page](https://developers.facebook.com/support/)'s community support or report a bug.

This is a community server side SDK and I have no connection to Facebook. This is not the place to ask questions about the Graph API itself.
