### ISSUE TITLE
facebook-node-sdk does not work in strict mode due to missing variable declaration

### ISSUE THREAD

**Issue by alarner** [node-facebook/facebook-node-sdk#22]
I get the following error when trying to use this library in strict mode:

parsedQuery is not defined

ReferenceError: parsedQuery is not defined
node_modules/fb/fb.js:277:25

**Comment by dantman** [comment]
How did this make it through release... oh, this library never used "use strict";

Ok, I'll merge that commit. And then I'll refactor the entire library. I'm going to ditch the coding style that the library came with and use my personal preferences; which are ones I can eslint and include lint errors for mistakes like this as part of tests.

**Comment by alarner** [comment]
:+1: sounds great! Thanks for maintaining this package

**Comment by dantman** [comment]
Ok, merged, linting added to tests/CI, and `1.0.2` released.
