### ISSUE TITLE
Type field isn't recognized in "not_replied" events calls

### ISSUE THREAD

**Issue by adamboazbecker** [node-facebook/facebook-node-sdk#39]
Hi all,

I wish to collect all of the events a user is associated with - even the ones that are "not_replied". But for some reason, the "type" field doesn't seem to be registered.

Facebook says that the usual endpoint:

`GET /v2.5/{user-id}/events HTTP/1.1`
`Host: graph.facebook.com`

doesn't include those events a user has not replied to, for which reason we need to add `type:enum{attending, created, declined, maybe, not_replied}` [[source]] (https://developers.facebook.com/docs/graph-api/reference/user/events/).

I tried adding the type in two ways (neither of which worked):

1. `FB.api('/'+user_id+'/events',{type:'not_replied'},function (res) {...`

2. `FB.api('', 'post', {batch: [{ method: 'get', relative_url: '/'+user_id+'/events',type:'not_replied'}]},function(res){...`

Any ideas why the call doesn't register the type?

**Comment by dantman** [comment]
I'm not sure why the first doesn't work, that's supposed to be the right way to do params. Could you try your test again with `DEBUG=fb:req`, that should echo some debug lines saying what FB api requests are made.

For the second one the object should be `{ method: 'get', relative_url: '/'+user_id+'/events?type=not_replied'}`.

**Comment by adamboazbecker** [comment]
Thank you so much @dantman.

For some reason, I couldn't quite place the DEBUG=fb:req - I'm not sure I knew how to place it right. But the syntax you suggested for the batch requests worked perfectly.

Thanks again!
