### ISSUE TITLE
Unable to get accessToken as it is passed to node as a # Hash

### ISSUE THREAD

**Issue by jamiehutber** [node-facebook/facebook-node-sdk#40]
I am trying to get the access token but as it passed to the callback url as a hash tag I don't have access to this/

````
            FB.api('oauth/access_token', {
                client_id: config.facebook.clientID,
                client_secret: config.facebook.clientSecret,
                grant_type: 'client_credentials'
            }, function (data) {
                if(!data || data.error) {
                    console.log(!data ? 'error occurred' : data.error);
                    return;
                }
                var accessToken = data.access_token;

                accessToken //Is my client ID and a random string starting with an _ (underscore)

                var body = 'My first post using facebook-node-sdk';
                FB.api('me/feed', 'post', { message: body }, function (res) {
                    if(!res || res.error) {
                        console.log(!res ? 'error occurred' : res.error);
                        return;
                    }
                    console.log('Post Id: ' + res.id);
                });
                res.redirect('/post/firsttime/success?facebookIsDoingSomething'); //the real access token is attached to '/post/firsttime/success?facebookIsDoingSomething#access_token=theRealTokenHere'
            });
````

I have previously given access to my app by manually opening up the dialogue and giving permissions.

**Comment by dantman** [comment]
Your example makes no sense.

* Calling oauth/access_token generates an **app** access token for server-server calls that are not authorized to do anything on behalf of any user.
* me/feed is called without passing an access token to it
* Likewise the app access token isn't authorized to call me/feed on behalf of anyone
* res.redirect is called outside of the me/feedback callback; exclaiming that the post was a success without waiting for the API call to finish and tell you if it succeeded or failed (and in this case guarantee a fail with an unauthorized error)
* And the comment on the redirect line makes no sense, this is a redirect from your server not a return_url response from Facebook, so it makes that the access_token would be in the url.

**Comment by jamiehutber** [comment]
ha, thanks for the fast reply.

Ignoring my hacking code to try and get it working. Your first line answers my question. I am to believe that we get the access token from the front end and then post to the users wall?

If this is the case I am sorry for creating a ticket for this. Maybe I hadn't read the documentation properly.

**Comment by dantman** [comment]
Yes, you need to get a user access token using a separate method, then you can pass that to your `FB.api` calls to do things on behalf of the user.

If you want to login using the login dialog:
* use Facebook's JS SDK (that's the client JS SDK for use in browsers) to login with FB.login
* Get the accessToken from the response and POST it to your server
* Use this SDK's `FB.api('debug_token', {input_token: ..., access_token: ...}, ...)` to verify the token belongs to your app
* The access token you get is only valid for a few hours, so [extend the access token](https://github.com/node-facebook/facebook-node-sdk#extend-expiry-time-of-the-access-token) to get a long lived token good for about 60 days.
 
If you want to do this without client side JS, you can "[Manually Build a Login Flow](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow)":
* Use `FB.getLoginUrl` to generate the `dialog/oauth` you need to redirect to (be sure to use the state param properly for security).
* [Exchange code for access token](https://github.com/node-facebook/facebook-node-sdk#exchange-code-for-access-token) to get the access token
* Use `FB.api('debug_token', {input_token: ..., access_token: ...}, ...)` to verify the token belongs to your app

**Comment by akhilkailas** [comment]
whenever try to run the sample app i get these error.

Error: Cannot find module '../../fb'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\nodejs\scrumptious\app.js:3:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

i am using node version 5.7.0 (Stable)

**Comment by dcohenb** [comment]
@akhilkailas 
You need to change the requires to the correct ones
for start update `FB = require('../../fb')` to `FB = require('fb')`
