### ISSUE TITLE
Couldn't install optional dependency net

### ISSUE THREAD

**Issue by honzapospi** [node-facebook/facebook-node-sdk#41]
Hello, during installation I got WARN:

> npm WARN install Couldn't install optional dependency: Unsupported
> myapp@1.0.0 /www/javasc/app/project
> └── net@1.0.2

Then when I start app I got: 
> bundle.js:38846 Uncaught Error: Cannot find module "net".

Node: v5.4.1 
bundled by webpack

**Comment by dantman** [comment]
I'm not sure how what you're reporting is related to `fb`.

* That dependency graph seems to indicate `net` is a direct dependency of `myapp` not a `fb` dependency.
* I don't understand what webpack has to do with this; this is intended to be run server-side directly through node, not bundled into the browser bundles.
* `require('net')` is a Node.js built-in module, it doesn't make any sense to try installing it through npm and if it's at all possible to use client-side then bundlers should already have handling to include a browser version of it

**Comment by honzapospi** [comment]
Sorry I expected there is invalid dependency "net", but it was only wrong installed, after I deleted node_modules and run install again it fixed this problem.
