### ISSUE TITLE
server issue in sample

### ISSUE THREAD

**Issue by akhilkailas** [node-facebook/facebook-node-sdk#42]
Error: Cannot find module '../../fb'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\nodejs\scrumptious\app.js:3:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

whenever i try to run sample app.js i get the above error

**Comment by dantman** [comment]
Sorry, tbh I haven't put any effort into trying to maintain the sample app. I'd rather maintain the docs, but I've been hesitant to simply delete the sample app.

**Comment by akhilkailas** [comment]
@dantman  i am learner in nodejs.so can i get the fb profile picture through this sdk is there any option for that if that please let me know sir.

**Comment by dantman** [comment]
This SDK just lets you make Facebook/Graph API calls. Lookup the information for what you want to do in [Facebook's Graph API Documentation](https://developers.facebook.com/docs/graph-api). For the most part making API calls using this SDK is the same as doing them using Facebook's own "JavaScript SDK", which has examples in Facebook's documentation. But in general it's a simple matter of turning the url into the API path and parameters (query or post).

The API call to get a profile picture is `/v{version}/{user-id}/picture?redirect=false`, so for the current user ("me") that would be `FB.api('/me/picture', {redirect: false}, cb);` using this server side SDK. Be sure to include an access_token as a parameter.

"How to do this in the Graph API" questions are best asked [on StackOverflow](https://stackoverflow.com/questions/tagged/facebook).

**Comment by BlueT** [comment]
@akhilkailas #66 fixed that.

**Comment by BlueT** [comment]
Samples has been removed in #92
This issue remain unfixed but became invalid.

**Comment by dantman** [comment]
Due to the issues I outlined in #48 I'm just removing `samples/` for 2.0.0.

#91 describes an alternative that may be more useful than the sample app ever helped anyone.
