### ISSUE TITLE
Upload photos fail

### ISSUE THREAD

**Issue by kalvin29** [node-facebook/facebook-node-sdk#43]
Below function will get error: (#324) Requires upload file. 

FB.api('me/photo', 'post', { source: fs.createReadStream('my-vacation.jpg'), caption: 'My vacation' }, function (res) {
  if(!res || res.error) {
    console.log(!res ? 'error occurred' : res.error);
    return;
  }
  console.log('Post Id: ' + res.post_id);
});

**Comment by dantman** [comment]
What version are you using?

File upload support was only added in `1.1.0-alpha1`.
