### ISSUE TITLE
Fate of the sample app

### ISSUE THREAD

**Issue by dantman** [node-facebook/facebook-node-sdk#48]
Could everyone who has tried to use the sample app included in the repo (and failed since it's unmaintained) comment on what reason you were using it for.

I'm not currently maintaining the sample app in this repo and am currently trying to decide if there is enough purpose to try and clean it up or if I should just remove it.

CC: @akhilkailas @bresson

---

My personal thoughts have been that there is little value sample app:
- This is an api library, not a visual one; so visiting the sample in your browser and logging in tells you nothing about how the library works.
- Sample apps don't make good examples for api libraries: You have to read through a pile of unrelated boilerplate to see how the library is being used and the ways it is used are very limited. The README examples we have are more useful than that.
- The sample app is written using express; at one point express could have been considered "the" node web framework, but now express has gotten stale and after the drama doesn't seem to be moving forward to the next release while other frameworks like koa and hapi have grown up enough that they are just as notable as express when picking a framework now. You also may not be using express with the node callback the sample app uses. So the example usage only shows you a very narrow way in how the library might be used.
- The sample app contains a pile of references from the Thuzi days:
  - Hardcoded appId and appSecret values referring to a Facebook App controlled by Thuzi
  - References to Thuzi's unmaintained facebook-winjs-sdk and its sample app
  - Hardcoded references to a herokuapp controlled by Thuzi
- The sample app is written with a number of terrible practices to use as an example for someone learning how to code a site:
  - No CSRF protection in the app
  - String interpolated html
  - String interpolated messages with no i18n
  - Outdated client side web development practices in the form of a liberal use of jQuery and a bit of mustache templates.

**Comment by BlueT** [comment]
@dantman thanks for the efforts you put on this repo!
Instead of closing it, maybe you can just merge those PR and add some collaborators to reduce the load on your shoulder, let contributors to improve what was not good enough. :-)

**Comment by dantman** [comment]
@BlueT So far no one has bothered to fully fix the issues with the sample app. A few have simply patched over it so that it runs, but it still relies on Thuzi controlled services and references that we have no control over.
