### ISSUE TITLE
import SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by jBachalo** [node-facebook/facebook-node-sdk#58]
When trying to run the Scrumptious example get the following error

```
-node-sdk-master/src/fb.js:2
import Promise from 'any-promise';
^^^^^^

SyntaxError: Unexpected reserved word
```

My node skills are still at intermediate level but guess I need to incorporate the babel module or??
Also the pathing in the scrumptious app.js slightly incorrect.

`    FB            = require('../../fb'),`
should be
`    FB            = require('../../src/fb'),`

**Comment by dantman** [comment]
Please see #42 and #48.

The sample app is not maintained.
