### ISSUE TITLE
Batch Post fs.createReadStream Issue!

### ISSUE THREAD

**Issue by rsflow** [node-facebook/facebook-node-sdk#59]
Hi,

I keep getting an error with batch requests saying `Error: ENOENT: no such file or directory, open '0'` for every item in the array so `open '1'` etc. I tried it with a single item array which I previously uploaded with a solo request but the same error occurred. 

Thank You!

**Comment by dantman** [comment]
What code are you using and what version of the library?

**Comment by rsflow** [comment]
I am using v1.1.1.
```javascript
FB.api('', 'post', {
      batch: [
         {
         method: 'post',
         relative_url: 'me/videos',
         source: FS.createReadStream(locations[0])
        }
  ]
  }, function(res) {
      ...
  })

```
Where `locations[0]` is the location of a file which I previously uploaded successfully with a single post request.

**Comment by dantman** [comment]
File upload params cannot be used inside the `batch` array.

In the Facebook API parameters like `batch` are sent as JSON so it's impossible for a file upload to be part of that.

Please see Facebook's API documentation:
https://developers.facebook.com/docs/graph-api/making-multiple-requests/#binary

When you want to batch upload files, you use FS.createReadStream with a different parameter name (e.g. `file1`) and then in the appropriate batch object you pass a `attached_files` parameter with the parameter name of the file as the value.
```js
FB.api('', 'post', {
    batch: [
      {
        method: 'post',
        relative_url: 'me/videos',
        attached_files: 'file1'
      }
    ],
    file1: FS.createReadStream(locations[0])
  }, function(res) {
    ...
  });
```

**Comment by rsflow** [comment]
Aaa ok that's why ... thank you very much I really appreciate it. :)
Do you want me to add this to the documentation or is it ok.
