### ISSUE TITLE
FB.api inside Promises!

### ISSUE THREAD

**Issue by rsflow** [node-facebook/facebook-node-sdk#60]
Hey @dantman ,

I have a function that calls the FB.api to get some video info from a batch of videos. 

When I call it directly like this `getVideosInfo(ids)` I get all the data. 

But, when I call it like this I get only 2/4 parameters.
```javascript
doA() 
.then(res1 => doB(res1))
.then(ids => getVideosInfo(ids))
.catch(err => console.log(err))

```

Do you have any idea what could be happening?

Thank You!

**Comment by dantman** [comment]
No, it shouldn't be anything related to the library or promises.

The closest idea I can think of is that one of the requests is being paginated.

**Comment by rsflow** [comment]
Even `doB` is a FB.api function ... which performs a batch `post` and returns the `ids` array (max 3 elements). This is really strange.
All the functions `doB` and `getVideosInfo ` are wrapped in Promises and the resolve is always in the end of the FB.api callback.

**Comment by rsflow** [comment]
*So I request from 4 videos to give me the `title, picture, source, id` and I get back 4 object with only the `title` and a strange `.gif` as picture.

**Comment by rsflow** [comment]
Hey @dantman ,
Look what happened .. the first call `doB ` that uploaded videos did return the video ids back but `facebook` needs an extra 15sec to update the databsase so the `getVideosInfo ` would always return corrupted data. Put a `delay()` on `doB` and all set.
Thank you! :)
