### ISSUE TITLE
Q: typescript definition files?

### ISSUE THREAD

**Issue by stevethecollier** [node-facebook/facebook-node-sdk#63]
I'm going to start building the def files, but I was wondering if anybody had already written them and for whatever reason didn't include in readme or def typed repo.

**Comment by dantman** [comment]
See #46 and feel free to review and test it.

**Comment by kari0003** [comment]
Hi!
Any progress with this? I would love if the new defs would be available.
I have tried the definitely typed package, but it is outdated as well.
Thanks in advance ^.^

**Comment by dantman** [comment]
Sorry, I haven't gone in to try out type definitions myself. I'm also a little on the fence on how to ideally handle this because the current PR is for Typescript but if I add types it would be ideal to also handle flow. Perhaps even putting types directly into the code.

**Comment by dantman** [comment]
I'm closing this in favour of the #167 issue which covers both Flow and TypeScript.

I do not wish to make a release of this package with support for one type ecosystem but not the other. Type definitions for both Flow and TypeScript should be written simultaneously.
