### ISSUE TITLE
Set language

### ISSUE THREAD

**Issue by logicsb** [node-facebook/facebook-node-sdk#69]
I need call graph API with pt_BR language. But i don't see any method to set this.

Thanks.

**Comment by dantman** [comment]
If you simply need a lang or language header, simply pass it as a param in `FB.api(path[, 'post], {...parameters})` like other parameters.

If you need control of something else like `Accepts-Language`, please point me to the Graph API documentation that requires it.

**Comment by logicsb** [comment]
Thanks @dantman works fine with parameters but the parameter name is "locale" not "language or lang" and locale format is ISO "pt_BR".
