### ISSUE TITLE
Paging?

### ISSUE THREAD

**Issue by leegee** [node-facebook/facebook-node-sdk#70]
Are there any plans to add paging support?

**Comment by dantman** [comment]
@leegee In what way? Paging is already possible, the same way as you do in Facebook's own SDK.

**Comment by leegee** [comment]
I can just pass the paging.next to FB.api as a URI?  I shall try when I
can, thank you.

**Comment by dantman** [comment]
@leegee Omit the initial part of the url, just use the path and query, or use the path and turn the query into an object to use with params.

But the easiest method would just be to use `paging.cursors.{before,after}` instead of the `paging.{previous,next}` urls.

**Comment by leegee** [comment]
No cursors coming back, but using 'next' works perfectly, thank you!

**Comment by nirmalgoswami** [comment]
@leegee can you paste your solution

**Comment by nirmalgoswami** [comment]
i am using `fb.api(response.paging.next, function (res) {{)` but no luck

**Comment by dantman** [comment]
@nirmalgoswami Don't forget the rest of my instructions.
> Omit the initial part of the url, just use the path and query, or use the path and turn the query into an object to use with params.

`paging.next` alone won't be in the proper format, you need to strip out the base part of the url.

**Comment by nirmalgoswami** [comment]
@dantman thanks for reply,

it working now using following approach

```
var url = response.paging.next.split('/events')[1];
fb.api('me/events'+url, function (res) {
```

**Comment by woutr** [comment]
You could also use the default node url module

```
const url = require('url');
const nextUrl = url.parse(res.paging.next);

console.log(nextUrl.search);
```
