### ISSUE TITLE
FQL Doesn't Work Due to Incorrect API

### ISSUE THREAD

**Issue by aeolingamenfel** [node-facebook/facebook-node-sdk#71]
When I try to run an FQL query, I get a `(#12) fql is deprecated for versions v2.1 and higher` error. Even when I set my API version to 2.0, I still get this error. 

---

**My Code:**

```
FB.options({version: 'v2.0'});
FB.setAccessToken("MyAccessToken");

// later in the code...

FB.api("fql", {
            q: "MyFQLQuery", // removed FQL query for brevity
}, (res) => {
    // my code to handle the result
});
```

**Comment by dantman** [comment]
v2.0 of the graph api reached its end of life on August 7, 2016 and was terminated by Facebook.

You cannot make FQL queries by setting the version to 2.0 anymore. Additionally 2.1 will be terminated at the end of this month.

**Comment by aeolingamenfel** [comment]
Alright, good to know. @dantman just a heads up: Your npm page is out of date, and was where I was getting documentation on; it still lists [FQL examples](https://www.npmjs.com/package/fb#facebook-query-language-fql).

**Comment by dantman** [comment]
The SDK still has the old code to make FQL requests, Facebook only killed 2.0 recently.
