### ISSUE TITLE
Inspecting Access Tokens

### ISSUE THREAD

**Issue by don4of4** [node-facebook/facebook-node-sdk#74]
Hello there,

Is there a function to validate an access token?  I would think this is fairly common use case, but I don't see it in the docs.

In order to validate that an access token is associated with an app you are supposed to do:
```
GET graph.facebook.com/debug_token?
     input_token={token-to-inspect}
     &access_token={app-token-or-admin-token}
```
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#checktoken

**Comment by dantman** [comment]
@don4of4 No, just make the API request yourself.

`FB.api('debug_token', { input_token: ..., access_token })`.

There are no shortcut methods in the SDK.
