### ISSUE TITLE
refresh a token

### ISSUE THREAD

**Issue by wyklif** [node-facebook/facebook-node-sdk#79]
how do i handle checking token expiration and refreshing them using this

**Comment by dantman** [comment]
Refreshing is already documented:
https://github.com/node-facebook/facebook-node-sdk#extend-expiry-time-of-the-access-token

Accessing debug is basically the same:
```js
FB.api('debug_token', {
  input_token: ...
  access_token: ...
});
```

The answer for any similar question is pretty much, just read the Facebook Graph/OAuth api documentation and look at the URL they give you; Look at the path and pass it as the first parameter, stripping out any `/v#.#` before it; If it's a POST or DELETE pass the method as the next argument; And pass any query or post parameters as an object as the next argument.
