### ISSUE TITLE
How do I give the permission to use graph api?

### ISSUE THREAD

**Issue by henrykapostel** [node-facebook/facebook-node-sdk#81]
I am going to use graph api but it requires some permissions.
while I checking the examples of this, I haven't found the set of permission.

**Comment by dantman** [comment]
@henrykapostel You need to get an access token by sending the user through a login flow.

Exactly how you do this is mostly out of the scope of this sdk. You can either login client side using Facebook's client side SDK or use the [manual login flow](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow) ([FB.getLoginUrl](https://github.com/node-facebook/facebook-node-sdk#manual-login-flow) can help generate the redirect url).
