### ISSUE TITLE
Page usage header

### ISSUE THREAD

**Issue by Amoki** [node-facebook/facebook-node-sdk#83]
Facebook can send some useful information in the header of the response (in my use case: https://developers.facebook.com/docs/graph-api/advanced/rate-limiting) and there is no way to retrieve them.

It could be nice to be able to get the original Request response object.

Would a PR be welcomed? 
Something like that would be ok?
```javascript
// src/fb.js:383
if ( isOAuthRequest && response && response.statusCode === 200 &&
	response.headers && /.*text\/plain.*/.test(response.headers['content-type'])) {
	// Parse the querystring body used before v2.3
	cb(parseOAuthApiResponse(body), response);
} else {
	let json;
	try {
		json = JSON.parse(body);
	} catch (ex) {
		// sometimes FB is has API errors that return HTML and a message
		// of "Sorry, something went wrong". These are infrequent and unpredictable but
		// let's not let them blow up our application.
		json = {
			error: {
				code: 'JSONPARSE',
				Error: ex
			}
		};
	}
	cb(json, response);
}
```
 Or eventually enabling the raw response with an option?

**Comment by dantman** [comment]
Passing a second callback parameter is a non-starter, that would be incompatible with/break the promise interface. And exposing the full response would just be a hack.

One possibility I could think of would be to always parse the `X-{App,Page}-Usage` header and store the rate limit data. Then you could use a separate method to get the rate limit data and freshness afterwards.
