### ISSUE TITLE
Inspecting Access Tokens

### ISSUE THREAD

**Issue by JonasWestAlro** [node-facebook/facebook-node-sdk#88]
Hi, 

I want to use this API feature: 
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#checktoken 

Can this library be used for that?

**Comment by dantman** [comment]
All the SDK does is make API calls to the graph API, so all you do is translate the API call the Facebook documentation describes to a FB.api call:

`graph.facebook.com/debug_token?input_token={token-to-inspect}&access_token={app-token-or-admin-token}` ->
```js
FB.api('/debug_token', {
  input_token: '{token-to-inspect}',
  access_token: '{app-token-or-admin-token}'
});
```
