### ISSUE TITLE
create app objects

### ISSUE THREAD

**Issue by CraigglesO** [node-facebook/facebook-node-sdk#98]
https://developers.facebook.com/docs/sharing/opengraph/object-api

Is this supported with this npm module? I can't figure it out.

edit - i think i just need ot set the path to "/me/objects/"

**Comment by dantman** [comment]
> edit - i think i just need ot set the path to "/me/objects/"

Yes, theoretically that is all that's needed. All of `FB.api`'s requests go to `graph.facebook.com`. The only modification to the path is that the graph api version is added: So `"/app/objects/books.book"` actually makes a call to something like `https://graph.facebook.com/v2.3/app/objects/books.book`.
