### ISSUE TITLE
problem with session kinda cute bug xD

### ISSUE THREAD

**Issue by Dj-jom2x** [node-facebook/facebook-node-sdk#99]
```
           fb.api('oauth/access_token', {
                   ....
                }, function (fb_response) {
                    if (!fb_response || fb_response.error) {
                        console.log(!res ? 'error occurred' : res.error);
                        return;
                    }
                    req.session.auth_type = "FB";
                    req.session.access_token = fb_response.access_token;
                    req.session.expired_token = fb_response.expires ? fb_response.expires : 0;
                    console.log(req.session);
                });
```

the console at the top it shows the cookies together with the session .. but if you access this **req** outside the  **function (fb_response)** 

it only shows the cookies xD the session is gone .. but still exist if you access it 
inside **function (fb_response)** 

output inside **function (fb_response)** 

  ```
Session {
cookie:
   { path: '/',
     _expires: 2017-06-02T21:50:59.733Z,
     originalMaxAge: 2628000000,
     httpOnly: true },
  auth_type: 'FB',
  access_token: 'my token here', 
  expired : 0,
```

output outside **function (fb_response)** 

```
Session {
  cookie:
   { path: '/',
     _expires: 2017-06-02T21:42:59.301Z,
     originalMaxAge: 2628000000,
     httpOnly: true } }
```

btw im using express   **app.get('/auth _thingy', function (req, res) {}**

**Comment by dantman** [comment]
How does this have anything to do with this SDK?

You are setting `req.session.*` in an asynchronous callback. If you access it out side of the callback then you are accessing it **before** the response from the API happens.

**Comment by Dj-jom2x** [comment]
ow xD sorry  its just auto save is not working inside that  asynchronous callback  i have to put this after i modified the session inside of it " req.session.save();" xD i'm just getting used to auto save my bad xD

**Comment by dantman** [comment]
iirc express is supposed to have a different format for asynchronous responses that should work with the auto save.
